services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS zeeguu_test;" -uroot
  - mysql -e "grant all on zeeguu_test.* to 'zeeguu_test'@'localhost' identified by 'zeeguu_test';" -uroot
  - pip3 install jieba3k
  - pip install coveralls
  - pip install -r requirements.txt

language: python
python:
  - "3.6"

install: "python setup.py develop"

script:
  - "export ZEEGUU_WEB_CONFIG=`pwd`/default_web.cfg && python -m zeeguu_web.app"
  - "./run_tests.sh"
